### ISSUE TITLE
1.6 setup contains wrong ES

### ISSUE THREAD

**Issue by billxiao** [rgl/elasticsearch-setup#15]
After installed 1.6 setup, I still saw the ES is 1.5.1, either in the response msg for GET request http://localhost:9200/ or in Marvel console. Please check what's wrong with my installation.

**Comment by rgl** [comment]
Did you have a previous install? What files are inside the lib directory?

**Comment by billxiao** [comment]
Yes, I did. Did you suggest the newer installation would not override previously installed ES?

**Comment by billxiao** [comment]
Oh, I found both es-1.5.1.jar and es-1.6.0.jar are in the lib folder. So ES chose older one to run? After stopping ES service, I manually deleted es-1.5.1.jar and restarted ES service, then the returned version number is 1.6.0. So the two jars cannot coexist in the lib folder, or ES would choose older one to run.

**Comment by rgl** [comment]
It will not. You have to uninstall the previous version first. If you changed the configuration, you should also make a backup of your configuration files before uninstall.

**Comment by billxiao** [comment]
Can the installer first detect previously installed ES and uninstall it if found?

**Comment by rgl** [comment]
Patches are welcome ;-)
